language: python
python:
  - "2.6"
  - "2.7"
install: 
  - "pip install -r requirements.freeze"
  - "pip install -r requirements.tests.freeze"
  - "pip install -e ./client"
  - "pip install -e ./server"
  - "pip install -e ./common"
script: "nosetests -w server"
